services:
  - type: web
    name: excel-duplicate-remover
    env: python
    runtime: python-3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."
